[package]
name = "lithos-engine-config"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[dependencies]
config = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
lithos-engine-memory = { path = "../memory" }