[package]
name = "lithos-engine-jobs"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[dependencies]
crossbeam = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
lithos-engine-memory = { path = "../memory" }

[features]
default = []